export const jsonData = {
  medicalUploadImg_length: 0,
  DeptResultC: [
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '参与态度题（Att）',
      group_name: '心理检测',
      item_name: 'Att',
      id: 'X000000002'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '焦虑状态（Anx-s）',
      group_name: '心理检测',
      item_name: 'Anx_s',
      id: 'X000000008'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '焦虑性人格（Anx）',
      group_name: '心理检测',
      item_name: 'Anx',
      id: 'X000000017'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '自杀意念（Sui-s）',
      group_name: '心理检测',
      item_name: 'Sui_s',
      id: 'X000000003'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '自杀倾向性人格（Sui）',
      group_name: '心理检测',
      item_name: 'Sui',
      id: 'X000000020'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '强迫状态（Obs-s）',
      group_name: '心理检测',
      item_name: 'Obs_s',
      id: 'X000000007'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '强迫症性人格（Obs）',
      group_name: '心理检测',
      item_name: 'Obs',
      id: 'X000000019'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '抑郁状态（Dep-s）',
      group_name: '心理检测',
      item_name: 'Dep_s',
      id: 'X000000009'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '抑郁性人格（Dep）',
      group_name: '心理检测',
      item_name: 'Dep',
      id: 'X000000018'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '精神病状态（Psy-s）',
      group_name: '心理检测',
      item_name: 'Psy_s',
      id: 'X000000010'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '神经质（Net）',
      group_name: '心理检测',
      item_name: 'Net',
      id: 'X000000011'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '敏感质（Set）',
      group_name: '心理检测',
      item_name: 'Set',
      id: 'X000000012'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '分离质（Dit）',
      group_name: '心理检测',
      item_name: 'Dit',
      id: 'X000000013'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '反社会性（Ant-s）',
      group_name: '心理检测',
      item_name: 'Ant_s',
      id: 'X000000004'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '偏离质（Dev）',
      group_name: '心理检测',
      item_name: 'Dev',
      id: 'X000000014'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '冲动质（Imp）',
      group_name: '心理检测',
      item_name: 'Imp',
      id: 'X000000015'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '悖逆质（Ant）',
      group_name: '心理检测',
      item_name: 'Ant',
      id: 'X000000016'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '躯体化（Som-s）',
      group_name: '心理检测',
      item_name: 'Som_s',
      id: 'X000000006'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '睡眠状况（Sle-s）',
      group_name: '心理检测',
      item_name: 'Sle_s',
      id: 'X000000005'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '心理检测室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      check_man: '杨劲晋',
      item_nameaa: '机检结果',
      group_name: '心理检测',
      item_name: 'resultCode',
      id: 'X000000001'
    }
  ],
  DeptResultB: [
    {
      initial_diagnose: '未见异常',
      dept_name: '心电图室',
      medical_value: '未见异常',
      check_date: '2024-11-11',
      tips_content: ' ',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '12导联心电图',
      item_name: '心电图检查'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '放射科',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: ' ',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '胸部正侧位片',
      item_name: '胸部正侧位片'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '超声影像科',
      medical_value: '未见异常',
      check_date: '2024-11-11',
      tips_content: ' ',
      check_man: '武志宏',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '双肾超声检查',
      item_name: '双肾彩超'
    },
    {
      initial_diagnose: '肝胆脾胰彩色多普勒超声：轻度脂肪肝',
      dept_name: '超声影像科',
      medical_value: '轻度脂肪肝',
      check_date: '2024-11-11',
      tips_content: ' ',
      check_man: '武志宏',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '肝胆脾胰超声检查',
      item_name: '肝胆脾胰彩色多普勒超声'
    }
  ],
  userJ: {
    origin_class: ' 　',
    smoking_habits_id: '　',
    exercise_method_id: '　',
    disease_suggset: '　',
    summary_suggest:
      '1、中性细胞百分率偏低:\r\n此结果会受病毒感染影响，建议复查，如持续异常请到内科咨询诊治。\r\n\r\n2、尿酸偏高:\r\n此项检查是评价肾功能的指标之一，尿酸偏高说明您有患痛风病的倾向。请您控制动物内脏及海产品的摄入量，定期复查。\r\n\r\n',
    exam_method_id: '门诊',
    datetype: 2,
    sex: '男',
    top_unit_id: '战略支援部队',
    current_class: '　',
    educational_status: '　',
    alergy_drugs_otheryw: '  ',
    no_check_reasons_id: '　',
    people_type: '军（警）士',
    branch_hospital_name: '中国人民解放军63710部队医院',
    approve_date: '2024-11-11',
    config_value:
      '感谢您对我们体检工作的支持!&#xd;\n    我们需要提示您注意的是：本次体检反映的是您当前的健康状况。因人体存在个体生物差异及您选择的检查项目并未涵盖全身所有脏器。因此医生所做的医学诊断和健康状况建议，是依据您的陈述和本次检查的结果综合分析评估而产生的。我们建议您对异常的结果进行相关的进一步检查或跟踪复查。',
    grade_of_duty_type: 1,
    birth_place: '山西省',
    nation: '汉族',
    asreal_name: '段京涛',
    summary_date: '2024-11-11',
    sexa: '男',
    family_disease: '  ',
    bingzhong_type: '　',
    drinking_status_id: '　',
    military_rank_id: '其他',
    start_date_of_work: '1905-07-08',
    location_id: '山西省',
    age: 27,
    grade_of_technic_id: '/',
    grade_of_duty_id: '无',
    com_no: '中国人民解放军63729部队',
    dietary_habit: '　',
    marital_status_id: '已婚',
    dili_didai: '　',
    medical_no: '24004696',
    archive_no: '140123199704230210',
    occupation_arms: ' ',
    tel: '18306890522',
    home_town: '山西省',
    birthday: '1997-04-23',
    yiliao_daiyu: '　',
    approve_man: '孙明继',
    blood_type_id: 'B型',
    real_name: '段京涛',
    dili_fenbu: '　',
    id_card: '140123199704230210',
    zhiye_type: '　',
    working_status_id: '在职',
    retire_date: '　',
    qihou_didai: '　',
    special_environment: '  ',
    shengyu_qingkuang: '　',
    qinwu_type: '　',
    adress: '　',
    summary_man: '张明浩'
  },
  DeptResultA: [
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '0.4',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '%',
      reference_range: '0～1',
      group_name: '血常规检查',
      item_name: '嗜碱细胞百分率'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '0.02',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '10^9/L',
      reference_range: '0～0.06',
      group_name: '血常规检查',
      item_name: '嗜碱细胞绝对数'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '165',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'g/L',
      reference_range: '130～175',
      group_name: '血常规检查',
      item_name: '血红蛋白测定（HB）'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '218',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '*10^9/L',
      reference_range: '125～350',
      group_name: '血常规检查',
      item_name: '血小板计数（PLT）'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '40',
      check_date: '2024-11-01',
      tips_content: '↓',
      check_man: '王迪迪',
      item_unit_name: '%',
      reference_range: '40～75',
      group_name: '血常规检查',
      item_name: '中性细胞百分率'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '1.9',
      check_date: '2024-11-01',
      tips_content: '↓',
      check_man: '王迪迪',
      item_unit_name: '*10^9/L',
      reference_range: '1.8～6.3',
      group_name: '血常规检查',
      item_name: '中性细胞绝对数'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '5.29',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '*10^12/L',
      reference_range: '4.3～5.8',
      group_name: '血常规检查',
      item_name: '红细胞计数（RBC）'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '46',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '%',
      reference_range: '20～50',
      group_name: '血常规检查',
      item_name: '淋巴细胞百分率'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '2.2',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '*10^9/L',
      reference_range: '1.1～3.2',
      group_name: '血常规检查',
      item_name: '淋巴细胞绝对数'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '90.5',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'fL',
      reference_range: '82～100',
      group_name: '血常规检查',
      item_name: '平均红细胞容积'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '10.4',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'fg',
      reference_range: '6～13',
      group_name: '血常规检查',
      item_name: '平均血小板体积'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '31.2',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'pg',
      reference_range: '27～34',
      group_name: '血常规检查',
      item_name: 'MCH'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '344',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'g/L',
      reference_range: '316～354',
      group_name: '血常规检查',
      item_name: 'MCHC'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '4.8',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '*10^9/L',
      reference_range: '3.5～9.5',
      group_name: '血常规检查',
      item_name: '白细胞计数（WBC）'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '11.5',
      check_date: '2024-11-01',
      tips_content: '↑',
      check_man: '王迪迪',
      item_unit_name: '%',
      reference_range: '3～10',
      group_name: '血常规检查',
      item_name: '单核细胞百分率'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '0.55',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '10^9/L',
      reference_range: '0.1～0.6',
      group_name: '血常规检查',
      item_name: '单核细胞绝对数'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '48',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '%',
      reference_range: '40～50',
      group_name: '血常规检查',
      item_name: '红细胞比积测定（HCT）'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '0.13',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '%',
      reference_range: '11.5～14.2',
      group_name: '血常规检查',
      item_name: '红细胞分布宽度CV'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '2.9',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '%',
      reference_range: '0.4～8',
      group_name: '血常规检查',
      item_name: '嗜酸细胞百分率'
    },
    {
      initial_diagnose:
        '1.中性细胞百分率偏低：40\r\n2.中性细胞绝对数偏低：1.9\r\n3.单核细胞百分率偏高：11.5\r\n',
      dept_name: '临检室',
      medical_value: '0.14',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: '10^9/L',
      reference_range: '0.02～0.52',
      group_name: '血常规检查',
      item_name: '嗜酸细胞绝对数'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: '1.005～1.03',
      group_name: '尿液常规检查',
      item_name: '尿比密'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿胆红素（BIL）'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: 'umol/L',
      reference_range: '3.2～16',
      group_name: '尿液常规检查',
      item_name: '尿胆原'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿葡萄糖（GLU）'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿酮体（KET）'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿亚硝酸盐（NIT）'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: '5～9',
      group_name: '尿液常规检查',
      item_name: '酸碱度（PH）'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿蛋白质'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿红细胞'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿白细胞（WBC）'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '尿液常规检查',
      item_name: '尿管型'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: '个/HP',
      reference_range: ' ',
      group_name: '粪便常规检查',
      item_name: '大便常规粪便虫卵'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '粪便常规检查',
      item_name: '性状'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '粪便常规检查',
      item_name: '大便潜血试验☆'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '粪便常规检查',
      item_name: '粪便白细胞'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '粪便常规检查',
      item_name: '粪便红细胞'
    },
    {
      initial_diagnose: '放弃检查:自愿放弃',
      dept_name: '临检室',
      medical_value: '放弃检查',
      check_date: '2024-11-11',
      tips_content: '　',
      check_man: '杨劲晋',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '粪便常规检查',
      item_name: '颜色'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '14.8',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'μmol/L',
      reference_range: '3.42～20.52',
      group_name: '肝功能检查',
      item_name: '总胆红素（TBIL）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '69.7',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'g/L',
      reference_range: '65～85',
      group_name: '肝功能检查',
      item_name: '血清总蛋白（TP）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '47.2',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'g/L',
      reference_range: '40～55',
      group_name: '肝功能检查',
      item_name: '血清白蛋白（ALB）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '2.7',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'μmol/L',
      reference_range: '0～5',
      group_name: '肝功能检查',
      item_name: '直接胆红素（DBIL）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '43',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'U/L',
      reference_range: '10～60',
      group_name: '肝功能检查',
      item_name: 'γ-谷氨酰转肽酶（γ-GT）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '83',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'U/L',
      reference_range: '35～100',
      group_name: '肝功能检查',
      item_name: '碱性磷酸酶（ALP）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '31',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'U/L',
      reference_range: '9～50',
      group_name: '肝功能检查',
      item_name: '丙氨酸氨基转移酶（ALT）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '生化室',
      medical_value: '19',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'U/L',
      reference_range: '15～40',
      group_name: '肝功能检查',
      item_name: '天冬氨酸基转移酶（AST）'
    },
    {
      initial_diagnose: '尿酸（UA）偏高：463\r\n',
      dept_name: '生化室',
      medical_value: '82',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'μmol/L',
      reference_range: '45～110',
      group_name: '肾功能检查',
      item_name: '肌酐（CRE）'
    },
    {
      initial_diagnose: '尿酸（UA）偏高：463\r\n',
      dept_name: '生化室',
      medical_value: '463',
      check_date: '2024-11-01',
      tips_content: '↑',
      check_man: '王迪迪',
      item_unit_name: 'umol/L',
      reference_range: '140～400',
      group_name: '肾功能检查',
      item_name: '尿酸（UA）'
    },
    {
      initial_diagnose: '尿酸（UA）偏高：463\r\n',
      dept_name: '生化室',
      medical_value: '7.14',
      check_date: '2024-11-01',
      tips_content: '　',
      check_man: '王迪迪',
      item_unit_name: 'mmol/L',
      reference_range: '2.5～6.3',
      group_name: '肾功能检查',
      item_name: '尿素氮（BUN）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '病毒室',
      medical_value: '阴性(-)',
      check_date: '2024-11-04',
      tips_content: '　',
      check_man: '王静',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '血清四项检查',
      item_name: '梅毒螺旋体特异抗体测定'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '病毒室',
      medical_value: '阴性(-)',
      check_date: '2024-11-04',
      tips_content: '　',
      check_man: '王静',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '血清四项检查',
      item_name: '人免疫缺陷病毒抗体测定（HIVAb）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '病毒室',
      medical_value: '阴性(-)',
      check_date: '2024-11-04',
      tips_content: '　',
      check_man: '王静',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '血清四项检查',
      item_name: '乙型肝炎表面抗原（HBsAg）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '病毒室',
      medical_value: '阴性(-)',
      check_date: '2024-11-04',
      tips_content: '　',
      check_man: '王静',
      item_unit_name: 'S/CO',
      reference_range: '0～1',
      group_name: '血清四项检查',
      item_name: '丙型肝炎抗体测定（Anti-HCV）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '一般情况',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: 'cm',
      reference_range: ' ',
      group_name: '一般检查',
      item_name: '身高'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '一般情况',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: 'kg',
      reference_range: ' ',
      group_name: '一般检查',
      item_name: '体重'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '一般情况',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: 'mmHg',
      reference_range: '90～140',
      group_name: '一般检查',
      item_name: '收缩压'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '一般情况',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: 'mmHg',
      reference_range: '60～90',
      group_name: '一般检查',
      item_name: '舒张压'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '一般情况',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: '次/分',
      reference_range: '60～100',
      group_name: '一般检查',
      item_name: '脉搏'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '一般情况',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: 'cm',
      reference_range: ' ',
      group_name: '一般检查',
      item_name: '腰围'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '一般情况',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: 'kg/m2',
      reference_range: '18.5～24',
      group_name: '一般检查',
      item_name: '体重指数'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心前区隆起'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心尖搏动'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心尖搏动震颤'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心包摩擦音'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心界'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心律'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心音'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '病理性杂音'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '心包摩擦感'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '周围血管征'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '颈静脉怒张'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '血管检查等'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '颈部血管杂音'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科心血管系统检查',
      item_name: '双下肢水肿'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科呼吸系统检查',
      item_name: '胸廓外形'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科呼吸系统检查',
      item_name: '呼吸运动'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科呼吸系统检查',
      item_name: '肋间隙'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科呼吸系统检查',
      item_name: '语颤'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科呼吸系统检查',
      item_name: '胸膜摩擦感'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹部外形'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹壁静脉曲张'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹部包块'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹部压痛'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹部反跳痛'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹壁紧张度'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '肝脏'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹部莫菲氏征'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '脾脏'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '腹部移动性浊音'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '肾区叩击痛'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科消化系统检查',
      item_name: '肠鸣音'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科神经系统检查',
      item_name: '一般症状'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科神经系统检查',
      item_name: '意识内容及情感状态'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科神经系统检查',
      item_name: '颅神经'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科神经系统检查',
      item_name: '肌力和肌张力'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科神经系统检查',
      item_name: '运动功能'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科神经系统检查',
      item_name: '感觉功能'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '内科',
      medical_value: '未见异常',
      check_date: '2024-11-08',
      tips_content: '　',
      check_man: '张志刚',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '内科神经系统检查',
      item_name: '神经反射等'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科一般检查',
      item_name: '浅部淋巴结（颌下、锁骨上下、腋窝、腹股沟）'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科一般检查',
      item_name: '颈部'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科一般检查',
      item_name: '皮肤'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科一般检查',
      item_name: '腹股沟'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科一般检查',
      item_name: '肛门与直肠'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科一般检查',
      item_name: '下肢静脉'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '骨科检查',
      item_name: '脊柱'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '骨科检查',
      item_name: '四肢关节'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科泌尿系统检查',
      item_name: '精索'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科泌尿系统检查',
      item_name: '睾丸'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科泌尿系统检查',
      item_name: '附睾'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '外科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '高培岗',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '外科泌尿系统检查',
      item_name: '前列腺等'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '5.0',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '右眼裸眼视力'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '5.0',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '左眼裸眼视力'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '右眼矫正视力'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '左眼矫正视力'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '眼睑'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '眼球'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '结膜'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '角膜'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '前房'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '瞳孔'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '晶状体'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '玻璃体'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '眼科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '眼科检查',
      item_name: '眼底'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '外耳道'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '鼻腔鼻窦'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '鼓膜'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '听力'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '鼻咽部'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '扁桃体'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '咽喉部'
    },
    {
      initial_diagnose: '未见异常',
      dept_name: '耳鼻咽喉科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '孙剑雄',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '耳鼻喉科检查',
      item_name: '颈部淋巴结等'
    },
    {
      initial_diagnose: '左上4残根',
      dept_name: '口腔科',
      medical_value: '左上4残根',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '廖晓睿',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '口腔科检查',
      item_name: '牙体'
    },
    {
      initial_diagnose: '左上4残根',
      dept_name: '口腔科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '廖晓睿',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '口腔科检查',
      item_name: '牙周'
    },
    {
      initial_diagnose: '左上4残根',
      dept_name: '口腔科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '廖晓睿',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '口腔科检查',
      item_name: '口腔粘膜'
    },
    {
      initial_diagnose: '左上4残根',
      dept_name: '口腔科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '廖晓睿',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '口腔科检查',
      item_name: '颞颌关节'
    },
    {
      initial_diagnose: '左上4残根',
      dept_name: '口腔科',
      medical_value: '未见异常',
      check_date: '2024-11-07',
      tips_content: '　',
      check_man: '廖晓睿',
      item_unit_name: ' ',
      reference_range: ' ',
      group_name: '口腔科检查',
      item_name: '口腔颌面部'
    }
  ],
  phtos: [],
  user: {
    medical_date: '2024-10-23',
    title: '干 部 健 康 体 检 报 告',
    grade_of_duty: '无',
    real_name: '段京涛',
    branch_hospital_name: '中国人民解放军63710部队医院',
    begin_medical_date: '2024-10-23',
    sex: '男',
    age: '27岁',
    year: '2025',
    print_date: '2024-11-16',
    com_name: '中国人民解放军63729部队',
    outpatient_card_code: '0097004023',
    medical_no: '24004696'
  }
}
